[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
amm = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"

[[test.genesis]]
address = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
program = "fixtures/mercurial_vault.so"

[[test.genesis]]
address = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
program = "fixtures/amm.so"

[scripts]
test = "yarn run ts-mocha -t 1000000 -p ./tsconfig.json src/amm/tests/events.test.ts"
event-test = "yarn run ts-mocha -t 1000000 -p ./tsconfig.json src/amm/tests/events.test.ts"
